### ISSUE TITLE
Browser Push Notifications on Android

### ISSUE THREAD

**Issue by Isanderthul** [cipchk/ngx-notify#8]
I tested the demo page, https://cipchk.github.io/ngx-notify/ on my android phone, and Browser Push notifications do not work. I am running Chrome 67.0.3396.87 on Android 8.0.0, One Plus 3T.

**Comment by cipchk** [comment]
Pls refer to [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API)
