### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by Succubussix** [cipchk/ngx-notify#9]
angular 7.. import it then put it into NgModule import

```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-notify/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

WARNING in ./node_modules/ngx-notify/node_modules/@angular/core/fesm5/core.js 4982:15-36
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ngx-notify/node_modules/@angular/core/fesm5/core.js 4994:15-102
Critical dependency: the request of a dependency is an expression
```

still works but i think this will fail on prod ....

**Comment by Succubussix** [comment]
I'm using ngx-notify  2.0.2

**Comment by Dj-jom2x** [comment]
i try to copy it directly i had this warning 

> WARNING in Circular dependency detected:
> src/app/components/misc/notify/notify-holder.component.ts -> src/app/components/misc/notify/notify.service.ts -> src/app/components/misc/notify/notify-holder.component.ts
> 
> WARNING in Circular dependency detected:
> src/app/components/misc/notify/notify.service.ts -> src/app/components/misc/notify/notify-holder.component.ts -> src/app/components/misc/notify/notify.service.ts
> 

i wonder how to fix this

**Comment by Succubussix** [comment]
nvm putting it manually works
